### ISSUE TITLE
Stopped detector: limit_exceeded_exception: AD memory circuit is broken.

### ISSUE THREAD

**Issue by ulasyuksel1979** [opendistro-for-elasticsearch/anomaly-detection#159]
**Describe the bug**
We are using ELK Stack 7.7.0 and installed OpenDistro AD plugin ver. 1.8 on top of ELK. 
We have defined a simple detector job running in 1 minute period. It successfully goes into "running" state  and works for a while and then fails into "Initialization failure" status after a few minutes.   In elastic log, there is and entry "[2020-06-17T00:12:48,653][ERROR][c.a.o.a.t.AnomalyResultTransportAction] [ISMLAELSLX12] Received an error from node WyJji2luRSW-MckiY6tD-w while fetching anomaly grade for jqEQpXIBVGwASRJcv1us" for failure and after that error mesage job has been disbled with "[2020-06-17T00:12:48,751][INFO ][c.a.o.a.AnomalyDetectorJobRunner] [ISMLAELSLX12] AD Job was disabled by JobRunner for jqEQpXIBVGwASRJcv1us" message.

**Other plugins installed**
opendistro-anomaly-detection
opendistro-job-scheduler
opendistro_alerting
opendistro_index_management
opendistro_performance_analyzer
opendistro_security
opendistro_sql

**To Reproduce**

Go to AD page and under Detectors section, just run the defined job.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59475285/84861901-ca044e80-b07a-11ea-9a38-636c6ef7ed02.png)
![image](https://user-images.githubusercontent.com/59475285/84861935-ddafb500-b07a-11ea-8927-c0817bde53d0.png)
![image](https://user-images.githubusercontent.com/59475285/84861969-f029ee80-b07a-11ea-8646-21c7ed8c4cbc.png)
![image](https://user-images.githubusercontent.com/59475285/84862077-30896c80-b07b-11ea-92ac-3d579b488c26.png)

**Desktop (please complete the following information):**

**Additional context**
We have recently upgrade our system from ELK 7.6.1 with AD 1.7 to ELK 7.7.0 with AD 1.8. this jog was running successfully in previous version. Also, I've seen a similar bug specifying limited resources (1 processor and a small amount of memory) but our system has plenty amount of resources. We have 16 Elasticsearch node on virtual machines and each has 12 core with 32 GB of memory. Cpu consumption is around %30 and JVM memory consumption is around %60.

**Comment by kaituo** [comment]
Circuit breaker is broken when heap memory usage exceeds 85% and AD job would be disabled because of that.  It is possible at one point your heap memory usage exceeded 85% and get back to around 60%.

The fix can be two fold:
First, only disable AD job after circuit breaker is broken for a consecutive number of times.
Second, add setting for enable/disable  disabling AD job because of memory circuit breaker.

What do you think?

**Comment by ulasyuksel1979** [comment]
Hi,
Those two layer of approach will probably handle most failure cases and gives the control to the user, it works for a while.

I have checked each detector memory usage and it was really small around 6-7 MB in total which i have taken those values in AD api command outputs. What is your main concern about memory usage? I mean which item consumes the memory too much, detector itself or running jobs agg process(sum, average, max,vb)?
If your main concern is detector itself, it would be better to create memory usage limits for each detector to have a better control. On the other, if you are considering lots of periodic jobs running in each minutes and they perhaps consumes too much memory then i think it is an elasticsearch issue, and it should be tuned on elasticsearch site.

Thanks for your response

**Comment by kaituo** [comment]
The goal of circuit breaker is to prioritize the basic ES functions, like data ingestion, when the load is heavy, since we are running on data nodes, not standalone ML node. 

My main concern of memory usage is what you said: models in memory and the memory used to running queries periodically.

We do have memory usage limit for each detector: each detector cannot take more than 5 features and a detector's model per node cannot exceed 0.02% of heap memory.  

As for periodic memory usage due to query running, Elasticsearch's own circuit breaker can throttle queries running, but it won't terminate our models.  Our own circuit breaker will.
