### ISSUE TITLE
Filter limitations

### ISSUE THREAD

**Issue by spoilerdo** [opendistro-for-elasticsearch/anomaly-detection#397]
**Is your feature request related to a problem? Please describe.**
I read in the documentation that a detector can have a maximum of 5 filters, why is that?

**Describe the solution you'd like**
Off course, it would be nice to have unlimited filters.

**Describe alternatives you've considered**
Give a detailed description in the documentation of why the max is 5 filters.

**Additional context**
This is not really a feature request but more of a question.
Sorry in advance for abusing the issue system for my question, I didn't know how to ask my question otherwise.

**Comment by kaituo** [comment]
1. The more features (what you call filters), the more likely the possible impact to precision/recall. It is [the curse of dimensionality](https://en.wikipedia.org/wiki/Curse_of_dimensionality). If the raw data has good quality, the effect is minor. If the raw data has a lot of noise, the impact is more significant because more noises mean the model has more difficulty distinguishing anomaly signal from noise. Also, for multi-feature models, the models detect anomalies within each feature and the correlational anomalies among features. The anomalies within each feature would have to be bigger than a single-feature model for the model to detect it. The reason is the same: the model has more difficulty distinguishing per feature anomaly from correlation anomalies.

2. We have a dynamic setting for you to adjust the limit. Check opendistro.anomaly_detection.max_anomaly_features [here](https://opendistro.github.io/for-elasticsearch-docs/docs/ad/settings/).

3. You can ask questions in our [forum](https://discuss.opendistrocommunity.dev/c/use-this-category-for-all-questions-around-machine-learning-plugins/46).

**Comment by spoilerdo** [comment]
Thx for the quick response, this was a very clear answer. So my feature request would be to put this explanation in the documentation. If this is already in the documentation than I could not find it, and you can close the issue.

**Comment by kaituo** [comment]
sure, will add to the doc.

**Comment by kaituo** [comment]
added doc here: https://opendistro.github.io/for-elasticsearch-docs/docs/ad/

A multi-feature model correlates anomalies across all its features. The curse of dimensionality makes it less likely for multi-feature models to identify smaller anomalies as compared to a single-feature model. Adding more features might negatively impact the precision and recall of a model. A higher proportion of noise in your data might further amplify this negative impact. Selecting the optimal feature set is usually an iterative process. We recommend experimenting with a historical detector with different feature sets and checking the precision before moving on to real-time detectors. By default, the maximum number of features for a detector is 5. You can adjust this limit with the opendistro.anomaly_detection.max_anomaly_features setting.

**Comment by spoilerdo** [comment]
Perfect.
